# Optimaization_Statistics - HW01
## 황호석 (G202158009)

## example.1 suppose that Aij Bjk are well defined

In [1]:
import numpy as np
np.random.seed(1)
i = 8
j = 5
k = 2

A = np.random.normal(size = (i, j))
B = np.random.normal(size = (j, k))

print(A @ B)
print((A @ B).shape)

[[ 0.01777662 -3.86011842]
 [-0.86986343  5.99696392]
 [ 1.30529626 -4.68597173]
 [ 0.37331712  1.69203542]
 [-0.39416427  3.95140242]
 [ 0.18802039  0.75969531]
 [ 0.15219003 -1.80926589]
 [ 1.25519254  1.91492266]]
(8, 2)


## example.2 tr(AC) = tr(CA)

In [2]:

np.random.seed(2)
n = 4
p = 3
A = np.random.normal(size = (n, p)) # (4, 3)행렬
C = np.random.normal(size = (p, n)) # (3, 4)행렬
print(np.trace(A @ C)) 
print(np.trace(C @ A))  


-2.7383748488564343
-2.7383748488564343


## example.3 tr(A<sup>T</sup> * A) =∑i,j(A)<sup>2</sup>

In [3]:

print(np.trace(A.T @ A))
print(np.sum(A ** 2))


20.663133986126496
20.663133986126493


## example.4 exp(x<sup>T</sup>Ax) = exp(tr(Axx<sup>T</sup>))

In [7]:
np.random.seed(4)
n = 4
x = np.random.normal(size = (n, 1)) # x는 (n, 1)벡터
A = np.random.normal(size = (n, n))
print(np.exp(x.T @ A @ x))
print(np.exp(np.trace(A @ x @ x.T)))

[[0.11724974]]
0.11724974333230392


## example.5 If the inverse matrices exist,
## • (AB)<sup>-1</sup> =B<sup>-1</sup>A<sup>-1</sup>
## • (A<sup>T</sup>)<sup>-1</sup>= (A<sup>-1</sup>)<sup>T</sup>

In [11]:

n = 2
A = np.random.normal(size = (n, n))
B = np.random.normal(size = (n, n))

print(np.linalg.inv(A @ B),'\n') 
print(np.linalg.inv(B) @ np.linalg.inv(A),'\n')

print(np.linalg.inv(A.T),'\n')
print(np.linalg.inv(A).T)


[[ 97.0523667  -62.40975437]
 [ 39.55427605 -25.84095706]] 

[[ 97.0523667  -62.40975437]
 [ 39.55427605 -25.84095706]] 

[[13.99369229  3.527101  ]
 [-9.33787777 -1.52166103]] 

[[13.99369229  3.527101  ]
 [-9.33787777 -1.52166103]]


## example.6 Shur's lemma


In [64]:

A = np.matrix('1 2 ; 3 4') # 2 * 2 
B = np.matrix('3 6 9 ; 12 13 16') # 2 * 3
C = np.matrix('9 5 ; 3 4 ; 2 7') # 3 * 2
D = np.matrix('1 2 7; 3 4 21; 3 21 10') # 3 * 3

M = np.bmat( [[A, B], [C, D]] )
print(M.shape,'\n') # 5 * 5 행렬
M_inv = np.linalg.inv(M) # M 행렬의 역행렬
AIV = np.linalg.inv(A) # A행렬의 역행렬

print(AIV + AIV @ B @ np.linalg.inv(D - C @ AIV @ B) @ C @ AIV, '\n') # M 역행렬의 [0:2, 0:2] 와 같음
print(M_inv[0:2,0:2], '\n')

print(np.linalg.inv(D - C @ AIV @ B), '\n') # M 역핼영릐 [2:5, 2:5]와 같음
print(M_inv[2:5, 2:5], '\n')


(5, 5) 

[[ 1.12016974 -0.17027808]
 [-2.57078368  0.39256049]] 

[[ 1.12016974 -0.17027808]
 [-2.57078368  0.39256049]] 

[[-3.84615385e-02  8.69447454e-02  2.16684724e-02]
 [ 3.84615385e-02 -2.01968220e-01 -4.51426508e-02]
 [ 1.59591338e-18 -7.04225352e-03 -4.22535211e-02]] 

[[-3.84615385e-02  8.69447454e-02  2.16684724e-02]
 [ 3.84615385e-02 -2.01968220e-01 -4.51426508e-02]
 [-1.00857416e-17 -7.04225352e-03 -4.22535211e-02]] 

